spring:
  application:
    name: gateway-service-zuul
server:
  port: 8773
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    hello:
      path: /producer/**
      serviceId: service-hi
